// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbfwjiojsievpivacwno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiZndqaW9qc2lldnBpdmFjd25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjEzMTQsImV4cCI6MjA2NDkzNzMxNH0.CBGDpBpkf7aCYH3N6gqZpVqwkAiVDvmbb1_ZzNKO6yM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);